ขอขอบคุณที่ให้การสนับสนุนเนื้อหาฉบับแปลของเรา! 
การสนับสนุนทั้งหมดที่คุณให้กับเนื้อหาของเราจำเป็นต้องปฏิบัติตามแนวทางต่อไปนี้:
1. [คู่มือรูปแบบภาษาของ Microsoft](https://www.microsoft.com/Language/StyleGuides) ซึ่งจะอธิบายว่าข้อความควรมีรูปแบบอย่างไรเมื่อแปลจากภาษาอังกฤษเป็นภาษาอื่น
2. [พอร์ทัลภาษาของ Microsoft](https://www.microsoft.com/language) มี **คำศัพท์** เกี่ยวกับเทคโนโลยีในภาษาอังกฤษและคำแปลที่สอดคล้องกันสำหรับผลิตภัณฑ์ต่างๆ ของ Microsoft
ในขณะที่คุณเข้าร่วมชุมชนการแปลที่กำลังเติบโตขึ้นของเรา คุณสามารถดูข้อมูลเพิ่มเติมเกี่ยวกับโปรแกรมการแปลของชุมชนและวิธีอื่นๆ ที่คุณสามารถสนับสนุนโปรแกรมของเราได้ โดยเข้าไปที่ [วิกิพีเดียสำหรับชุมชนการแปล](https://github.com/Microsoft/Localization/wiki) เรายังจะแจ้งเกี่ยวกับกระบวนการอนุมัติคำขอดึงข้อมูลบนหน้านี้ เช่นเดียวกับเคล็ดลับ < การจัดการคำขอดึงข้อมูล > บางประการ
ให้การสนับสนุนอย่างต่อเนื่องและก้าวสู่ระดับที่สูงขึ้นในการจัดอันดับของ [กระดานผู้นำของผู้สนับสนุน](https://microsoftl10n.github.io/) เมื่อคุณได้รับรางวัลเป็นคะแนนการให้การสนับสนุน <การแปล> ของคุณ!

กลุ่มระหว่างประเทศเพื่อความสัมพันธ์ของนักพัฒนา Microsoft
